### ISSUE TITLE
Tests fail on Go1.20

### ISSUE THREAD

**Issue by zhsj** [gatherstars-com/jwz#6]
```
$ go version
go version go1.20rc3 linux/amd64
```

```
--- FAIL: TestThreader_ThreadSlice (0.00s)
    jwz_test.go:396: expected 2379 emails after threading, but got 135 back
--- FAIL: TestThreader_ThreadRoot (0.00s)
    jwz_test.go:449: expected 2379 emails after threading, but got 135 back
--- FAIL: ExampleThreader_ThreadSlice (0.00s)
got:
expected 2379 emails after threading, but got 135 back
want:
There are 2379 test emails
--- FAIL: ExampleThreader_ThreadRoot (0.00s)
got:
expected 2379 emails afer threading, but got 135 back
want:
There are 2379 test emails
--- FAIL: ExampleSort (0.00s)
got:
First node subject: 2002-09-05 22:42:38 +0000 UTC : [Spambayes] All but one testing
want:
First node subject: 2002-02-01 05:44:14 +0000 UTC : Please help a newbie compile mplayer :-)
--- FAIL: ExampleWalk_depth (0.00s)
got:
Walker walked 135 depth first
want:
Walker walked 2379 depth first
--- FAIL: ExampleWalk_breadth (0.00s)
got:
Walker walked 135 depth first
want:
Walker walked 2379 depth first
--- FAIL: ExampleCount (0.00s)
got:
There are 135 test emails
want:
There are 2379 test emails
FAIL
FAIL    github.com/gatherstars-com/jwz  0.183s
FAIL
```

Seems related to:

```
2023/01/16 15:04:37 cannot parse email file error = Failed to ReadParts: malformed MIME header line: From rssfeeds@jmason.org  Thu Oct 10 12:32:32 2002
```

**Comment by jimidle** [comment]
I will keep an eye on this, but 1.20 is not yet released of course, so I am loathe to spend time on it right now. It may have exposed an incorrect dependency on order, or something similar.

**Comment by jimidle** [comment]
Go 1.20 is now released, so I will check the tests with it once I have a chance to upgrade to 1.20. I do this via brew and it is always a few days behind the binary 'raw' release.

**Comment by zhsj** [comment]
Probably same as https://github.com/jhillyerd/enmime/issues/269

enmime now rejects invalid header as well.

**Comment by jimidle** [comment]
> Probably same as [jhillyerd/enmime#269](https://github.com/jhillyerd/enmime/issues/269)
> 
> enmime now rejects invalid header as well.

This could be related indeed. I will get to the bottom of this in the next few days and make a new release - there is one change in devel that has not been released yet. Time to release it.

**Comment by jimidle** [comment]
The test data was indeed malformed and enmime will now no longer deal with it. I agree with their reasoning and the headers in error (as well as invalid characters) would have been illegal even when these sample emails were created. I deliberately used old emails so we could detect such things as this. 

The email clients and servers that produced such badly formed emails are now long out of use by all but the most curmudgeonly old UNIX gits (not even me). So I think that we will require anyone wishing to parse and thread very old archives to perform a little preprocessing before passing them to this module.

**Comment by zhsj** [comment]
Looks like upstream is going to revert such change... https://github.com/golang/go/issues/60332

**Comment by jimidle** [comment]
> Looks like upstream is going to revert such change... [golang/go#60332](https://github.com/golang/go/issues/60332)

Yes - I won't put the malformed header tests back I think, but it means that if they revert the stricter interpretation, then this will also allow emime and jwz to parse such headers again. I sort-of agree though that we generally should be enforcing the RFCs - some really poor programming escaped into the wilds of email processing back in the day. Probably, in the main, because the RFCs were somewhat lacking in specificity, which was fixed a long time ago.

Thanks for the headsup!
